### ISSUE TITLE
Secondary ranges defined in module vs. outside process

### ISSUE THREAD

**Issue by brettcurtis** [terraform-google-modules/terraform-google-network#213]
Is it possible to support adding secondary ranges in the module as well as have things like kubernetes automatically add secondary ranges? 

If I do not set any secondary ranges and then build a k8s cluster on this VPC the subsequent terraform runs will try to remove the secondary ranges k8s created.

**Comment by bharathkkb** [comment]
Hi @brettcurtis 
You may have to use the native resource instead of this module and then utilize [lifecycle ignore_changes](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to support this. We have some examples using our GKE module on how to create secondary ranges and spin up a cluster [here](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_regional_with_networking/main.tf) if that is viable.

**Comment by brettcurtis** [comment]
Yeah, right now I'm doing it similar to the example you shared. I did try adding lifecycle ignore with just the secondary ranges after I build my k8s cluster on this network that solved the problem of subsequent runs, but then if I added a secondary range to the module nothing was added. I think it's just the nature of terraform and it being authoritative. I think we just simply need to say either all secondary ranges are done in the module or all are done outside it and we ignore_changes.

**Comment by morgante** [comment]
Instead of allowing GKE to auto-create secondary for you, we strongly encourage you to create the ranges yourself upfront and then pass the names to GKE (as is done in the [linked example](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/examples/simple_regional_with_networking/main.tf#L57)).

**Comment by brettcurtis** [comment]
Ok that's what I figured. It just requires the consumer of the two modules to be a bit more knowledgeable. Thanks for the feedback.
