### ISSUE TITLE
VPC - Private Service Connection - Allocate IP Range setup

### ISSUE THREAD

**Issue by wesleung** [terraform-google-modules/terraform-google-network#508]
### TL;DR

Using this network module, when creating a VPC, cannot find how to configure a new "Private Service Connection - Allocate IP Range".  If this configuration already exists, please point me to the settings.

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/datastream_private_connection
```

### Additional information

This IP range network is being used by SQL databases

**Comment by imrannayer** [comment]
https://github.com/terraform-google-modules/terraform-google-sql-db/tree/master/modules/private_service_access

**Comment by jeheyer** [comment]
Would be helpful to support this within this module though, since there's services other than CloudSQL that use PSA.  NetApp is another use case.  

https://github.com/aws2gcp/gcp-network-terraform/blob/main/vpc-network/ip_ranges.tf
https://github.com/aws2gcp/gcp-network-terraform/blob/main/vpc-network/service_networking.tf
